// introduce , reservation 매장 10개 이미지 포함
let stn = [
    {
        id: 1,
        name: '가좌 직영점',
        address: '인천 서구 가재울로54번길 15 1층 코웨이',
        img: '/images/store/store0.png',
        alt: '가좌 직영점',
        time: '11:00 - 20:00',
        close: '설 / 추석 당일만 휴무',
        park: '가능',
        tel: '032-820-6462',
    },
    {
        id: 2,
        name: '울산 직영점',
        address: '울산 남구 삼산중로 65 1층 코웨이',
        img: '/images/store/store1.png',
        alt: '울산 직영점',
        time: '11:00 - 20:00',
        close: '설 / 추석 당일만 휴무',
        park: '가능',
        tel: '052-269-9022',
    },
    {
        id: 3,
        name: '고양 직영점',
        address: '경기 고양시 덕양구 고양대로 1955 코웨이',
        img: '/images/store/store2.png',
        alt: '고양 직영점',
        time: '10:00 - 10:00',
        close: '연중무휴',
        park: '가능',
        tel: '02-381-9925',
    },
    {
        id: 4,
        name: '분당 직영점',
        address: '경기 성남시 분당구 황새울로 348 1층 코웨이',
        img: '/images/store/store3.png',
        alt: '분당 직영점',
        time: '11:00 - 20:00',
        close: '설 / 추석 당일만 휴무',
        park: '가능',
        tel: '031-724-4686',
    },
    {
        id: 5,
        name: '구월 직영점',
        address: '인천 남동구 남동대로 767 코웨이',
        img: '/images/store/store4.png',
        alt: '구월 직영점',
        time: '11:00 - 20:00',
        close: '설 / 추석 당일만 휴무',
        park: '가능',
        tel: '032-713-4674',
    },
    {
        id: 6,
        name: '노원 직영점',
        address: '서울 노원구 동일로 1091 코웨이',
        img: '/images/store/store5.png',
        alt: '노원 직영점',
        time: '11:00 - 20:00',
        close: '설 / 추석 당일만 휴무',
        park: '가능',
        tel: '02-3296-5435',
    },
    {
        id: 7,
        name: '용산 직영점',
        address: '서울 용산구 한강대로23길 55 5층 코웨이',
        img: '/images/store/store6.png',
        alt: '용산 직영점',
        time: '11:00 - 20:00',
        close: '설 / 추석 당일만 휴무',
        park: '가능',
        tel: '02-6953-9618',
    },
    {
        id: 8,
        name: '수원 직영점',
        address: '경기 수원시 영통구 덕영대로 1513 코웨이',
        img: '/images/store/store7.png',
        alt: '수원 직영점',
        time: '11:00 - 20:00',
        close: '설 / 추석 당일만 휴무',
        park: '가능',
        tel: '031-8067-8645',
    },
    {
        id: 9,
        name: '용인 직영점',
        address: '경기 용인시 기흥구 신고매로 59 리빙파워센터 지하 3층 코웨이',
        img: '/images/store/store8.png',
        alt: '용인 직영점',
        time: '11:00 - 20:00',
        close: '설 / 추석 당일만 휴무',
        park: '가능',
        tel: '031-8067-7604',
    },
    {
        id: 10,
        name: '구로 직영점',
        address: '서울 구로구 디지털로26길 38 G타워 3층 코웨이',
        img: '/images/store/store9.png',
        alt: '구로 직영점',
        time: '11:00 - 20:00',
        close: '설 / 추석 당일만 휴무',
        park: '가능',
        tel: '02-2534-9507',
    },
];

// otherVendor 판매처 10개
// 지역 서울,인천,경기,부산
let ov = [
    {
        id: 1,
        name: '이마트 | 사상점',
        address: '부산광역시 사상구 광장로 17[이마트 사상점內 코웨이 매장]',
        tel: '051-329-1234',
        time: '운영 시간 : 10:00 ~ 21:00',
        closeDate: '휴무일 : 매장확인 필요',
        parking: '주차가능 여부 : 가능',
        class: 'class="type-distribution"',
        span: '유통점',
    },
    {
        id: 2,
        name: '이마트 | 왕십리점',
        address: '서울시 성동구 왕십리광장로 17(행당동) [이마트 왕십리점 內 코웨이 매장]',
        tel: '02-2200-1234',
        time: '운영 시간 : 10:30 ~ 23:00',
        closeDate: '휴무일 : 매장확인 필요',
        parking: '주차가능 여부 : 가능',
        class: 'type-distribution',
        span: '유통점',
    },
    {
        id: 3,
        name: '이마트 | 연수점',
        address: '인천시 연수구 경원대로 184(동춘동) [이마트 연수점 內 코웨이 매장]',
        tel: '032-820-1234',
        time: '운영 시간 : 10:00 ~ 23:00',
        closeDate: '휴무일 : 매장확인 필요',
        parking: '주차가능 여부 : 가능',
        class: 'type-distribution',
        span: '유통점',
    },
    {
        id: 4,
        name: '전시실 | 인천',
        address: '인천광역시 남동구 구월동 1146-10 삼성생명빌딩 20층 인천허브총국',
        tel: '032-431-1407',
        time: '운영 시간 : 09:00 ~ 18:00',
        closeDate: '휴무일 : 토요일,일요일,공휴일',
        parking: '주차가능 여부 : 가능',
        class: 'type-management-display',
        span: '직영전시점',
    },
    {
        id: 5,
        name: '이마트 | 연제점',
        address: '부산광역시 연제구 연수로 89(연산동) [이마트 연제점 內 코웨이 매장]',
        tel: '051-860-1234',
        time: '운영 시간 : 10:00 ~ 23:00',
        closeDate: '휴무일 : 매장확인 필요',
        parking: '주차가능 여부 : 가능',
        class: 'type-distribution',
        span: '유통점',
    },
    {
        id: 6,
        name: '전시실 | 경기북서',
        address: '경기도 고양시 일산동구 중앙로 1160(마두동) 오원프라자 2층 경기북서허브총국',
        tel: '031-908-0692',
        time: '운영 시간 : 09:00 ~ 18:00',
        closeDate: '휴무일 : 토요일,일요일,공휴일',
        parking: '주차가능 여부 : 가능',
        class: 'type-management-display',
        span: '직영전시점',
    },
    {
        id: 7,
        name: '이마트 | 서수원점',
        address: '경기도 수원시 권선구 수인로 291(구운동) [이마트 서수원점 內 코웨이 매장]',
        tel: '031-895-1234',
        time: '운영 시간 : 10:00 ~ 23:00',
        closeDate: '휴무일 : 매장확인 필요',
        parking: '주차가능 여부 : 가능',
        class: 'type-distribution',
        span: '유통점',
    },
    {
        id: 8,
        name: '하이마트 | 월드타워점',
        address: '서울 송파구 신천동 29 롯데월드몰 3층 (쇼핑몰)',
        tel: '02-3213-3000',
        time: '운영 시간 : 10:30 ~ 21:00',
        closeDate: '휴무일 : 매장확인 필요',
        parking: '주차가능 여부 : 가능',
        class: 'type-management-display',
        span: '직영전시점',
    },
];

let rpd = [
    {
        id: 1,
        name: '리클라이닝 안마베드',
        img: '/images/store/massageBed1.png',
        alt: '리클라이닝 안마베드',
    },
    { id: 2, name: '안마베드', img: '/images/store/massageBed2.png', alt: '안마베드' },
    { id: 3, name: '페블체어', img: '/images/store/massageChair1.png', alt: '페블체어' },
    { id: 4, name: '마인 플러스', img: '/images/store/massageChair2.png', alt: '마인 플러스' },
    { id: 5, name: '스마트 매트리스', img: '/images/store/mattress1.png', alt: '스마트 매트리스' },
    { id: 6, name: '매트리스', img: '/images/store/mattress2.png', alt: '매트리스' },
];

export { stn, ov, rpd };
