// 주방/생활가전
export const lifeEleData = [
    {
        id: 1,
        name: 'W 인덕션(3구)',
        key: 'CIP-30W',
        model: ['CIP-30WLS', 'CIP-30WGS', 'CIP-30WWS', 'CIP-30WPS'],
        color: ['#cddbe8', '#656667', '#eae7e0', '#eed4cf'],
        starPoint: 4.9,
        starCnt: 97,
        purPrice: 1620000,
        rentPrice: 22000,
        category: 'etc',
        new: true,
        best: true,
        purItem: true,
        rentItem: true,
        imgUrl: '../../images/products/lifeElc/CIP-30W/CIP-30WLS.png',
        displayImg: 2,
        lenterDiscount: 100000,
        moreOrder: 288540,
        haveCoway: 96180,
    },
    {
        id: 2,
        name: '프라임 인덕션 (3구)',
        key: 'NIP-31KE',
        model: 'NIP-31KE',
        color: 'black',
        starPoint: 4.9,
        starCnt: 49,
        purPrice: 1130000,
        rentPrice: 16400,
        category: 'electricRange',
        new: true,
        best: true,
        purItem: true,
        rentItem: true,
        imgUrl: '../../images/products/lifeElc/NIP-31KE/NIP-31KE.png',
        displayImg: 3,
        lenterDiscount: 100000,
        moreOrder: 206640,
        haveCoway: 68880,
    },
    {
        id: 3,
        name: '프라임 하이브리드 (인덕션 2구+ 하이라이트 1구)',
        key: 'NHP-31KE',
        model: 'NHP-31KE',
        color: 'black',
        starPoint: 4.9,
        starCnt: 62,
        purPrice: 910000,
        rentPrice: 12900,
        category: 'electricRange',
        new: true,
        best: true,
        purItem: true,
        rentItem: true,
        imgUrl: '../../images/products/lifeElc/NHP-31KE/NHP-31KE.png',
        displayImg: 3,
        lenterDiscount: 100000,
        moreOrder: 162540,
        haveCoway: 54180,
    },
    {
        id: 4,
        name: '프라임S 인덕션 (3구)',
        key: 'CIR-303',
        model: 'CIR-303',
        color: 'black',
        starPoint: 4.9,
        starCnt: 16,
        purPrice: 1450000,
        rentPrice: 19900,
        category: 'electricRange',
        new: true,
        best: true,
        purItem: true,
        rentItem: true,
        imgUrl: '../../images/products/lifeElc/CIR-303/CIR-303.png',
        displayImg: 3,
        lenterDiscount: 100000,
        moreOrder: 250740,
        haveCoway: 83580,
    },
    {
        id: 5,
        name: '프라임S 하이라이트 (3구)',
        key: 'CER-04',
        model: 'CER-04',
        color: 'black',
        starPoint: 5.0,
        starCnt: 22,
        purPrice: 970000,
        rentPrice: 14400,
        category: 'electricRange',
        new: true,
        best: false,
        purItem: true,
        rentItem: true,
        imgUrl: '../../images/products/lifeElc/CER-04/CER-04.png',
        displayImg: 3,
        lenterDiscount: 100000,
        moreOrder: 181440,
        haveCoway: 60480,
    },
    {
        id: 6,
        name: '프라임S 하이브리드 (인덕션 2구+ 하이라이트 1구)',
        key: 'CHR-04',
        model: 'CHR-04',
        color: 'black',
        starPoint: 4.9,
        starCnt: 30,
        purPrice: 1290000,
        rentPrice: 18900,
        category: 'electricRange',
        new: true,
        best: false,
        purItem: true,
        rentItem: true,
        imgUrl: '../../images/products/lifeElc/CHR-04/CHR-04.png',
        displayImg: 3,
        lenterDiscount: 100000,
        moreOrder: 238140,
        haveCoway: 79380,
    },
    {
        id: 7,
        name: '노블 인덕션 All-Free (4구)',
        key: 'CIR-F41',
        model: ['CIR-F41GS', 'CIR-F41PS', 'CIR-F41BS'],
        color: ['#5c5858', '#d8b6ac', '#e2dad1'],
        starPoint: 4.9,
        starCnt: 99,
        purPrice: 2390000,
        rentPrice: 27900,
        category: 'etc',
        new: false,
        best: false,
        purItem: true,
        rentItem: true,
        imgUrl: '../../images/products/lifeElc/CIR-F41/CIR-F41GS.png',
        displayImg: 6,
        lenterDiscount: 100000,
        moreOrder: 351540,
        haveCoway: 117180,
    },
    {
        id: 8,
        name: '노블 인덕션 All-Free 와이드 (6구,전기공사형)',
        key: 'CIR-F60GS',
        model: 'CIR-F60GS',
        color: 'black',
        starPoint: 5.0,
        starCnt: 1,
        purPrice: 4190000,
        rentPrice: 55900,
        category: 'electricRange',
        new: false,
        best: false,
        purItem: true,
        rentItem: true,
        imgUrl: '../../images/products/lifeElc/CIR-F60GS/CIR-F60GS.png',
        displayImg: 5,
        lenterDiscount: 100000,
        moreOrder: 704340,
        haveCoway: 234780,
    },
];

// 룰루비데/연수기
export const waterEleData = [
    {
        id: 1,
        name: '스스로케어 비데 리모트',
        key: 'BAS25-B',
        model: 'BAS25-B',
        color: 'white',
        starPoint: 5.0,
        starCnt: 61,
        purPrice: 850000,
        rentPrice: 24400,
        category: 'bidet',
        new: true,
        best: false,
        purItem: true,
        rentItem: true,
        imgUrl: '../images/products/lifeElc/BAS25-B/BAS25-B.png',
        displayImg: 3,
        lenterDiscount: 100000,
        moreOrder: 263520,
        haveCoway: 87840,
    },
    {
        id: 2,
        name: '프라임 비데',
        key: 'BA36-B',
        model: 'BA36-B',
        color: 'white',
        starPoint: 4.8,
        starCnt: 378,
        purPrice: 760000,
        rentPrice: 20400,
        category: 'bidet',
        new: true,
        best: false,
        purItem: true,
        rentItem: true,
        imgUrl: '../images/products/lifeElc/BA36-B/BA36-B.png',
        displayImg: 4,
        lenterDiscount: 100000,
        moreOrder: 220320,
        haveCoway: 73440,
    },
    {
        id: 3,
        name: '더블케어 플러스 비데',
        key: 'BAS38-B',
        model: 'BAS38-B',
        color: 'white',
        starPoint: 4.8,
        starCnt: 48,
        purPrice: 970000,
        rentPrice: 26900,
        category: 'bidet',
        new: true,
        best: false,
        purItem: true,
        rentItem: true,
        imgUrl: '../images/products/lifeElc/BAS38-B/BAS38-B.png',
        displayImg: 5,
        lenterDiscount: 100000,
        moreOrder: 290520,
        haveCoway: 96840,
    },
    {
        id: 4,
        name: '스타일케어 비데',
        key: 'BAS41-A',
        model: ['BAS41-A_GR', 'BAS41-A_PK', 'BAS41-A_GN'],
        color: ['#C7C8C7', '#CCBEB8', '#A0A99F'],
        starPoint: 4.9,
        starCnt: 322,
        purPrice: 800000,
        rentPrice: 19900,
        category: 'bidet',
        new: true,
        best: false,
        purItem: true,
        rentItem: true,
        imgUrl: '../images/products/lifeElc/BAS41-A/BAS41-A_GR.png',
        displayImg: 2,
        lenterDiscount: 100000,
        moreOrder: 214920,
        haveCoway: 71640,
    },
    {
        id: 5,
        name: '스스로케어 비데(일반형)',
        key: 'BAS40-A',
        model: 'BAS40-A',
        color: 'white',
        starPoint: 4.9,
        starCnt: 762,
        purPrice: 770000,
        rentPrice: 18400,
        category: 'bidet',
        new: true,
        best: false,
        purItem: true,
        rentItem: true,
        imgUrl: '../images/products/lifeElc/BAS40-A/BAS40-A.png',
        displayImg: 4,
        lenterDiscount: 100000,
        moreOrder: 198720,
        haveCoway: 66240,
    },
    {
        id: 6,
        name: '스킨플러스 연수기(수전일체형)',
        key: 'BB17-A',
        model: ['BB17-A_WT', 'BB17-A_GR'],
        color: ['#ffffff', '#7a7a7a'],
        starPoint: 4.5,
        starCnt: 20,
        purPrice: 1370000,
        rentPrice: 30900,
        category: 'trainingPeriod',
        new: true,
        best: false,
        purItem: true,
        rentItem: true,
        imgUrl: '../images/products/lifeElc/BB17-A/BB17-A_WT.png',
        displayImg: 2,
        lenterDiscount: 100000,
        moreOrder: 333720,
        haveCoway: 111240,
    },
    {
        id: 7,
        name: '스킨플러스 연수기(일반형)',
        key: 'BB16-A',
        model: ['BB16-A_WT', 'BB16-A_GR'],
        color: ['#ffffff', '#7a7a7a'],
        starPoint: 4.7,
        starCnt: 209,
        purPrice: 1180000,
        rentPrice: 27900,
        category: 'trainingPeriod',
        new: true,
        best: false,
        purItem: true,
        rentItem: true,
        imgUrl: '../images/products/lifeElc/BB16-A/BB16-A_WT.png',
        displayImg: 2,
        lenterDiscount: 100000,
        moreOrder: 301320,
        haveCoway: 100440,
    },
    {
        id: 8,
        name: '연수기(BB15-A)',
        key: 'BB15-A',
        model: 'BB15-A',
        color: 'white',
        starPoint: 4.9,
        starCnt: 636,
        purPrice: 810000,
        rentPrice: 26900,
        category: 'trainingPeriod',
        new: false,
        best: false,
        purItem: true,
        rentItem: true,
        imgUrl: '../images/products/lifeElc/BB15-A/BB15-A.png',
        displayImg: 2,
        lenterDiscount: 100000,
        moreOrder: 290520,
        haveCoway: 96840,
    },
];

// BEREX 매트리스/안마의자
export const berexEleData = [
    {
        id: 1,
        name: 'BEREX 안마의자 마인 플러스',
        key: 'MC-B02',
        model: ['MC-B02_BG', 'MC-B02_BK', 'MC-B02_BR', 'MC-B02_GR'],
        color: ['#a69e98', '#494a4e', '#7C595E', '#A4B2B6'],
        starPoint: 4.9,
        starCnt: 83,
        purPrice: 2290000,
        rentPrice: 44900,
        category: 'massageChair',
        new: true,
        best: false,
        purItem: true,
        rentItem: true,
        imgUrl: '/../images/products/lifeElc/MC-B02/MC-B02_BG.png',
        displayImg: 4,
        lenterDiscount: 100000,
        moreOrder: 404100,
        haveCoway: 134700,
    },
    {
        id: 2,
        name: 'BEREX 안마의자 마인2.0',
        key: 'MC-B03',
        model: ['MC-B03_BG', 'MC-B03_BK', 'MC-B03_BR', 'MC-B03_GR'],
        color: ['#a69e98', '#494a4e', '#7C595E', '#A4B2B6'],
        starPoint: 0,
        starCnt: 0,
        purPrice: 2290000,
        rentPrice: 44900,
        category: 'massageChair',
        new: true,
        best: true,
        purItem: true,
        rentItem: true,
        imgUrl: '/../images/products/lifeElc/MC-B03/MC-B03_BG.png',
        displayImg: 4,
        lenterDiscount: 100000,
        moreOrder: 404100,
        haveCoway: 134700,
    },
    {
        id: 3,
        name: 'BEREX 리클라이닝 안마베드',
        key: 'MB-M02',
        model: ['MB-M02_BG', 'MB-M02_BK', 'MB-M02_WT', 'MB-M02_BR'],
        color: ['#a69e98', '#494a4e', '#eae7db', '#997d65'],
        starPoint: 4.9,
        starCnt: 11,
        purPrice: 5670000,
        rentPrice: 80550,
        category: 'massageBed',
        new: true,
        best: false,
        purItem: true,
        rentItem: true,
        imgUrl: '/../images/products/lifeElc/MB-M02/MB-M02_BG.png',
        displayImg: 6,
        lenterDiscount: 100000,
        moreOrder: 1014930,
        haveCoway: 338310,
    },
    {
        id: 4,
        name: 'BEREX 척추베드',
        key: 'MB-C01',
        model: ['MB-C01_BG', 'MB-C01_BK', 'MB-C01_WT', 'MB-C01_BR'],
        color: ['#a69e98', '#494a4e', '#eae7db', '#997d65'],
        starPoint: 4.9,
        starCnt: 23,
        purPrice: 4000000,
        rentPrice: 29800,
        category: 'massageBed',
        new: true,
        best: true,
        purItem: true,
        rentItem: true,
        imgUrl: '/../images/products/lifeElc/MB-C01/MB-C01_BG.png',
        displayImg: 6,
        lenterDiscount: 100000,
        moreOrder: 697320,
        haveCoway: 232440,
    },
    {
        id: 5,
        name: 'BEREX 안마베드',
        key: 'MB-B01',
        model: ['MB-B01_BG', 'MB-B01_BK', 'MB-B01_WT', 'MB-B01_BR'],
        color: ['#a69e98', '#494a4e', '#eae7db', '#997d65'],
        starPoint: 4.9,
        starCnt: 126,
        purPrice: 4640000,
        rentPrice: 32600,
        category: 'massageBed',
        new: true,
        best: true,
        purItem: true,
        rentItem: true,
        imgUrl: '/../images/products/lifeElc/MB-C01/MB-C01_BG.png',
        displayImg: 6,
        lenterDiscount: 100000,
        moreOrder: 762840,
        haveCoway: 254280,
    },
    {
        id: 6,
        name: 'BEREX 안마의자 페블체어',
        key: 'MC-C01',
        model: ['MC-C01_GR', 'MC-C01_BG', 'MC-C01_PK', 'MC-C01_BU'],
        color: ['#d3d3d3', '#baa289', '#c09885', '#8f9fb5'],
        starPoint: 4.9,
        starCnt: 548,
        purPrice: 2350000,
        rentPrice: 49900,
        category: 'massageChair',
        new: true,
        best: true,
        purItem: true,
        rentItem: true,
        imgUrl: '/../images/products/lifeElc/MC-C01/MC-C01_GR.png',
        displayImg: 4,
        lenterDiscount: 100000,
        moreOrder: 449100,
        haveCoway: 149700,
    },
];

// 리퍼브 기획전
export const refurbData = [
    {
        id: 1,
        name: '프라임 비데(BA36-A_RA, 리퍼브 A등급)',
        key: 'BA36-A_RA',
        model: 'BA36-A_RA',
        color: 'white',
        starPoint: 4.8,
        starCnt: 6,
        purPrice: 400000,
        rentPrice: 17900,
        category: 'refurbBidet',
        new: false,
        best: false,
        refurb: true,
        purItem: true,
        rentItem: true,
        imgUrl: '/../images/products/lifeElc/BA36-A_RA/BA36-A_RA.png',
        displayImg: 3,
        lenterDiscount: 100000,
        moreOrder: 96660,
        haveCoway: 32220,
    },
    {
        id: 2,
        name: '워터스탠드 (리퍼브 A등급)',
        key: 'CHP-5710L-RA',
        model: 'CHP-5710L-RA',
        color: 'white',
        starPoint: 0,
        starCnt: 0,
        purPrice: 1000000,
        rentPrice: 25900,
        category: 'refurbTrainingPeriod',
        new: false,
        best: false,
        refurb: true,
        purItem: true,
        rentItem: true,
        imgUrl: '/../images/products/lifeElc/CHP-5710L-RA/CHP-5710L-RA.png',
        displayImg: 2,
        lenterDiscount: 100000,
        moreOrder: 139860,
        haveCoway: 46620,
    },
    {
        id: 3,
        name: '프라임 1.0 (리퍼브 A등급)',
        key: 'CHP-264L-RA',
        model: 'CHP-264L-RA',
        color: 'white',
        starPoint: 0,
        starCnt: 0,
        purPrice: 783000,
        rentPrice: 23900,
        category: 'refurbTrainingPeriod',
        new: false,
        best: false,
        refurb: true,
        purItem: true,
        rentItem: true,
        imgUrl: '/../images/products/lifeElc/CHP-264L-RA/CHP-264L-RA.png',
        displayImg: 2,
        lenterDiscount: 100000,
        moreOrder: 129060,
        haveCoway: 43020,
    },
    {
        id: 4,
        name: '스스로 케어 비데(BAS29-C_RA, 리퍼브 A등급)',
        key: 'BAS29-C-RA',
        model: 'BAS29-C-RA',
        color: 'white',
        starPoint: 5.0,
        starCnt: 5,
        purPrice: 412000,
        rentPrice: 18400,
        category: 'refurbBidet',
        new: false,
        best: false,
        refurb: true,
        purItem: true,
        rentItem: true,
        imgUrl: '/../images/products/lifeElc/BAS29-C-RA/BAS29-C-RA.png',
        displayImg: 3,
        lenterDiscount: 100000,
        moreOrder: 99360,
        haveCoway: 33120,
    },
    {
        id: 5,
        name: '스타일 케어 비데(BAS31-A_RA, 리퍼브 A등급)',
        key: 'BAS31-A-RA',
        model: 'BAS31-A-RA',
        color: 'white',
        starPoint: 5.0,
        starCnt: 1,
        purPrice: 449000,
        rentPrice: 19900,
        category: 'refurbBidet',
        new: false,
        best: false,
        refurb: true,
        purItem: true,
        rentItem: true,
        imgUrl: '/../images/products/lifeElc/BAS31-A-RA/BAS31-A-RA.png',
        displayImg: 3,
        lenterDiscount: 100000,
        moreOrder: 107460,
        haveCoway: 35820,
    },
];
